# Capstone Weekly Data Set Updater

In [1]:
import numpy as np
import pandas as pd

In [2]:
current_week = 7
previous_week = current_week - 1

In [3]:
import ast

# Path to input data.txt file
with open(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/inputs - week {current_week}.txt', 'r') as f:
    text_input = f.read()

#Clean text
text_input = text_input.replace("array(","").replace(")", "")
text_input = text_input.replace("]]","],").replace("[[","[")
text_input = text_input.replace("\n","")
text_input = (f"[{text_input}]")
text_input = text_input.replace("],]","]]")

text_input = text_input.strip()
data_input = ast.literal_eval(text_input)


# Path to output data.txt file
with open(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/outputs - week {current_week}.txt', 'r') as f:
    text_output = f.read()
print(repr(text_output))

#Clean text
text_output = text_output.replace("]\n[",", ")
text_output = text_output.replace("np.float64","")

text_output = text_output.strip()
data_output = ast.literal_eval(text_output)


'[np.float64(1.3343361655402784e-79), np.float64(-0.03462578421977675), np.float64(-0.09884205223592774), np.float64(-0.26823166241327057), np.float64(129.82271985576077), np.float64(-1.3711450885714167), np.float64(1.127291236972185), np.float64(9.7772314276134)]\n[np.float64(-1.0008031913361931e-121), np.float64(0.024600551480097158), np.float64(-0.06638200670116563), np.float64(-0.11103127782386535), np.float64(2808.931578800419), np.float64(-1.1171707823610078), np.float64(1.1653229165514087), np.float64(9.7744562610926)]\n[np.float64(2.4149318622360758e-36), np.float64(0.1109337917405185), np.float64(-0.08545748061096686), np.float64(0.11560165275106771), np.float64(2578.907278380477), np.float64(-0.2967920323841292), np.float64(1.7349317990608195), np.float64(9.5765911983411)]\n[np.float64(-0.0004202087946475647), np.float64(0.5531219637409615), np.float64(-0.030423451529225154), np.float64(-0.9603725589316308), np.float64(2736.463464894479), np.float64(-0.3319775131306024), np.f

## Function 1

In [4]:
# ==== Import Previous Data Sets ====

function1_inputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 1/function1_inputs_week{previous_week}.npy')
print('Inputs: \n',function1_inputs)

function1_outputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 1/function1_outputs_week{previous_week}.npy')
print('Outputs: \n',function1_outputs)


# ==== Import New Data ====

f1_new_inputs = np.array([np.float64(data_input[-8])])
f1_new_output = np.array([np.float64(data_output[-8])])


# ==== Join old and new data ====

function1_inputs_updated = np.vstack([function1_inputs, f1_new_inputs])
print('Updated inputs:\n', function1_inputs_updated)

function1_outputs_updated = np.concatenate((function1_outputs, f1_new_output))
print('Updated outputs:\n',function1_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 1/function1_inputs_week{current_week}', function1_inputs_updated)
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 1/function1_outputs_week{current_week}', function1_outputs_updated)

Inputs: 
 [[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.912815   0.808011  ]
 [0.406375   0.98      ]
 [0.832839   0.723797  ]
 [0.43       0.49      ]
 [0.774397   0.804657  ]]
Outputs: 
 [ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048  1.33433617e-079 -1.00080319e-121
  2.41493186e-036 -4.20208795e-004  6.01763969e-037]
Updated inputs:
 [[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.912815   0.808011  ]
 [0.406375   0.98      ]
 [0.832839   0.723797  ]
 

## Function 2

In [5]:

# ==== Import Previous Data Sets ====

function2_inputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 2/function2_inputs_week{previous_week}.npy')
print('Inputs: \n',function2_inputs)

function2_outputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 2/function2_outputs_week{previous_week}.npy')
print('Outputs: \n',function2_outputs)


# ==== Import New Data ====

f2_new_inputs = np.array([np.float64(data_input[-7])])
f2_new_output = np.array([np.float64(data_output[-7])])

# ==== Join old and new data ====

function2_inputs_updated = np.vstack([function2_inputs, f2_new_inputs])
print('Updated inputs:\n',function2_inputs_updated)

function2_outputs_updated = np.concatenate((function2_outputs, f2_new_output))
print('Updated outputs:\n',function2_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 2/function2_inputs_week{current_week}', function2_inputs_updated)
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 2/function2_outputs_week{current_week}', function2_outputs_updated)

Inputs: 
 [[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.21       0.8       ]
 [0.6        0.42      ]
 [0.800537   0.921613  ]
 [0.673479   0.928902  ]
 [0.68597    0.889318  ]]
Outputs: 
 [ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522 -0.03462578  0.02460055
  0.11093379  0.55312196  0.6022346 ]
Updated inputs:
 [[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.21       0.8       ]
 [0.6        0.42      ]
 [0.800537   0.921613  ]
 [0.673479   0.928902  ]
 [0.68597    0.889318  ]
 [0.19       0.64      ]]
U

## Function 3

In [6]:
# ==== Import Previous Data Sets ====

function3_inputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 3/function3_inputs_week{previous_week}.npy')
print('Inputs: \n',function3_inputs)

function3_outputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 3/function3_outputs_week{previous_week}.npy')
print('Outputs: \n',function3_outputs)


# ==== Import New Data ====

f3_new_inputs = np.array([np.float64(data_input[-6])])
f3_new_output = np.array([np.float64(data_output[-6])])


# ==== Join old and new data ====

function3_inputs_updated = np.vstack([function3_inputs, f3_new_inputs])
print('Updated inputs:\n',function3_inputs_updated)

function3_outputs_updated = np.concatenate((function3_outputs, f3_new_output))
print('Updated outputs:\n',function3_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name and path each week so old versions aren't overwritten.
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 3/function3_inputs_week{current_week}', function3_inputs_updated)
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 3/function3_outputs_week{current_week}', function3_outputs_updated)

Inputs: 
 [[0.17152521 0.34391687 0.2487372 ]
 [0.24211446 0.64407427 0.27243281]
 [0.53490572 0.39850092 0.17338873]
 [0.49258141 0.61159319 0.34017639]
 [0.13462167 0.21991724 0.45820622]
 [0.34552327 0.94135983 0.26936348]
 [0.15183663 0.43999062 0.99088187]
 [0.64550284 0.39714294 0.91977134]
 [0.74691195 0.28419631 0.22629985]
 [0.17047699 0.6970324  0.14916943]
 [0.22054934 0.29782524 0.34355534]
 [0.66601366 0.67198515 0.2462953 ]
 [0.04680895 0.23136024 0.77061759]
 [0.60009728 0.72513573 0.06608864]
 [0.96599485 0.86111969 0.56682913]
 [0.51764    0.004569   0.569925  ]
 [0.891717   0.852251   0.371034  ]
 [0.414483   0.061504   0.530133  ]
 [0.430025   0.43138    0.511326  ]
 [0.5048     0.719751   0.254471  ]]
Outputs: 
 [-0.1121222  -0.08796286 -0.11141465 -0.03483531 -0.04800758 -0.11062091
 -0.39892551 -0.11386851 -0.13146061 -0.09418956 -0.04694741 -0.10596504
 -0.11804826 -0.03637783 -0.05675837 -0.09884205 -0.06638201 -0.08545748
 -0.03042345 -0.11085593]
Updated input

## Function 4

In [7]:
# ==== Import Previous Data Sets ====

function4_inputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 4/function4_inputs_week{previous_week}.npy')
print('Inputs: \n',function4_inputs)

function4_outputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 4/function4_outputs_week{previous_week}.npy')
print('Outputs: \n',function4_outputs)


# ==== Import New Data ====

f4_new_inputs = np.array([np.float64(data_input[-5])])
f4_new_output = np.array([np.float64(data_output[-5])])


# ==== Join old and new data ====

function4_inputs_updated = np.vstack([function4_inputs, f4_new_inputs])
print('Updated inputs:\n',function4_inputs_updated)

function4_outputs_updated = np.concatenate((function4_outputs, f4_new_output))
print('Updated outputs:\n',function4_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 4/function4_inputs_week{current_week}', function4_inputs_updated)
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 4/function4_outputs_week{current_week}', function4_outputs_updated)

Inputs: 
 [[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0

## Function 5

In [8]:
# ==== Import Previous Data Sets ====

function5_inputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 5/function5_inputs_week{previous_week}.npy')
print('Inputs: \n',function5_inputs)

function5_outputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 5/function5_outputs_week{previous_week}.npy')
print('Outputs: \n',function5_outputs)


# ==== Import New Data ====

f5_new_inputs = np.array([np.float64(data_input[-4])])
f5_new_output = np.array([np.float64(data_output[-4])])


# ==== Join old and new data ====

function5_inputs_updated = np.vstack([function5_inputs, f5_new_inputs])
print('Updated inputs:\n',function5_inputs_updated)

function5_outputs_updated = np.concatenate((function5_outputs, f5_new_output))
print('Updated outputs:\n',function5_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 5/function5_inputs_week{current_week}', function5_inputs_updated)
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 5/function5_outputs_week{current_week}', function5_outputs_updated)

Inputs: 
 [[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]
 [0.39689    0.353366   0.237596   0.128478  ]
 [0

## Function 6

In [9]:
# ==== Import Previous Data Sets ====

function6_inputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 6/function6_inputs_week{previous_week}.npy')
print('Inputs: \n',function6_inputs)

function6_outputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 6/function6_outputs_week{previous_week}.npy')
print('Outputs: \n',function6_outputs)


# ==== Import New Data ====

f6_new_inputs = np.array([np.float64(data_input[-3])])
f6_new_output = np.array([np.float64(data_output[-3])])


# ==== Join old and new data ====

function6_inputs_updated = np.vstack([function6_inputs, f6_new_inputs])
print('Updated inputs:\n',function6_inputs_updated)

function6_outputs_updated = np.concatenate((function6_outputs, f6_new_output))
print('Updated outputs:\n',function6_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 6/function6_inputs_week{current_week}', function6_inputs_updated)
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 6/function6_outputs_week{current_week}', function6_outputs_updated)

Inputs: 
 [[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.

## Function 7

In [10]:
# ==== Import Previous Data Sets ====

function7_inputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 7/function7_inputs_week{previous_week}.npy')
print('Inputs: \n',function7_inputs)

function7_outputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 7/function7_outputs_week{previous_week}.npy')
print('Outputs: \n',function7_outputs)


# ==== Import New Data ====

f7_new_inputs = np.array([np.float64(data_input[-2])])
f7_new_output = np.array([np.float64(data_output[-2])])


# ==== Join old and new data ====

function7_inputs_updated = np.vstack([function7_inputs, f7_new_inputs])
print('Updated inputs:\n',function7_inputs_updated)

function7_outputs_updated = np.concatenate((function7_outputs, f7_new_output))
print('Updated outputs:\n',function7_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 7/function7_inputs_week{current_week}', function7_inputs_updated)
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 7/function7_outputs_week{current_week}', function7_outputs_updated)

Inputs: 
 [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 

## Function 8

In [11]:
# ==== Import Previous Data Sets ====

function8_inputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 8/function8_inputs_week{previous_week}.npy')
print('Inputs: \n',function8_inputs)

function8_outputs = np.load(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {previous_week}/Function 8/function8_outputs_week{previous_week}.npy')
print('Outputs: \n',function8_outputs)


# ==== Import New Data ====

f8_new_inputs = np.array([np.float64(data_input[-1])])
f8_new_output = np.array([np.float64(data_output[-1])])


# ==== Join old and new data ====

function8_inputs_updated = np.vstack([function8_inputs, f8_new_inputs])
print('Updated inputs:\n',function8_inputs_updated)

function8_outputs_updated = np.concatenate((function8_outputs, f8_new_output))
print('Updated outputs:\n',function8_outputs_updated)


# ==== Export Updated Data Sets as .npy files ====

# Make sure to change file name each week so old versions aren't overwritten.
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 8/function8_inputs_week{current_week}', function8_inputs_updated)
np.save(f'C:/Python/Ml and AI - Imperial/Capstone Project/Data Sets/Week {current_week}/Function 8/function8_outputs_week{current_week}', function8_outputs_updated)

Inputs: 
 [[0.60499445 0.29221502 0.90845275 0.35550624 0.20166872 0.57533801
  0.31031095 0.73428138]
 [0.17800696 0.56622265 0.99486184 0.21032501 0.32015266 0.70790879
  0.63538449 0.10713163]
 [0.00907698 0.81162615 0.52052036 0.07568668 0.26511183 0.09165169
  0.59241515 0.36732026]
 [0.50602816 0.65373012 0.36341078 0.17798105 0.0937283  0.19742533
  0.7558269  0.29247234]
 [0.35990926 0.24907568 0.49599717 0.70921498 0.11498719 0.28920692
  0.55729515 0.59388173]
 [0.77881834 0.0034195  0.33798313 0.51952778 0.82090699 0.53724669
  0.5513471  0.66003209]
 [0.90864932 0.0622497  0.23825955 0.76660355 0.13233596 0.99024381
  0.68806782 0.74249594]
 [0.58637144 0.88073573 0.74502075 0.54603485 0.00964888 0.74899176
  0.23090707 0.09791562]
 [0.76113733 0.85467239 0.38212433 0.33735198 0.68970832 0.30985305
  0.63137968 0.04195607]
 [0.9849332  0.69950626 0.9988855  0.18014846 0.58014315 0.23108719
  0.49082694 0.31368272]
 [0.11207131 0.43773566 0.59659878 0.59277563 0.22698177 0.4